import type { TableConfig } from "./table-registry";

/** Nhóm "Vật phẩm" + "Shop" — soát cột/PK từ `SHOW CREATE TABLE` (2026-09-26). */
export const ITEM_SHOP_TABLES: TableConfig[] = [
  {
    db: "game",
    table: "item",
    label: "Vật phẩm",
    group: "Vật phẩm",
    pk: ["itemId"],
    searchCols: ["itemId", "name"],
    refCheck: { playerColumn: "items", jsonKey: "itemTemplateId" },
    columns: [
      { name: "itemId", label: "ID", type: "int" },
      { name: "name", label: "Tên", type: "string" },
      { name: "description", label: "Mô tả", type: "string", long: true },
      { name: "type", label: "Loại", type: "int" },
      { name: "iconPath", label: "Đường dẫn icon", type: "string", nullable: true },
      { name: "frameImgPath", label: "Đường dẫn frame", type: "string", nullable: true },
      { name: "gender", label: "Giới tính (-1 = mọi giới)", type: "int" },
      { name: "isStackable", label: "Xếp chồng được", type: "bool" },
      { name: "itemOption", label: "itemOption (JSON id thuộc tính)", type: "json", nullable: true },
      { name: "itemOptionValue", label: "itemOptionValue (JSON giá trị)", type: "json", nullable: true },
      { name: "atkRange", label: "Khoảng atk (JSON)", type: "json", nullable: true },
      { name: "defRange", label: "Khoảng def (JSON)", type: "json", nullable: true },
      { name: "hpRange", label: "Khoảng hp (JSON)", type: "json", nullable: true },
      { name: "mpRange", label: "Khoảng mp (JSON)", type: "json", nullable: true },
      { name: "requireStr", label: "Yêu cầu STR", type: "int" },
      { name: "requireInt", label: "Yêu cầu INT", type: "int" },
      { name: "requireAgi", label: "Yêu cầu AGI", type: "int" },
      { name: "expire", label: "Hạn dùng (ms)", type: "bigint", nullable: true },
      { name: "isOnSky", label: "Bay được", type: "bool" },
      { name: "canTrade", label: "Giao dịch được", type: "bool" },
      { name: "petNClass", label: "Phái pet (-1 = mọi phái)", type: "int" },
      { name: "element", label: "Hệ (-1 = mọi hệ)", type: "int" },
      { name: "price", label: "Giá cơ bản", type: "int" },
    ],
  },
  {
    db: "game",
    table: "tier_item",
    label: "Nâng cấp vật phẩm (tier)",
    group: "Vật phẩm",
    pk: ["tierId"],
    autoIncrement: true,
    searchCols: ["tierId", "itemTemplateIdTier1", "itemTemplateIdTier2"],
    columns: [
      { name: "tierId", label: "ID", type: "int" },
      { name: "itemTemplateIdTier1", label: "Item gốc", type: "ref", ref: "item" },
      { name: "itemTemplateIdTier2", label: "Item nâng cấp", type: "ref", ref: "item" },
      { name: "percent", label: "Tỉ lệ % thành công", type: "float" },
    ],
  },
  {
    db: "game",
    table: "iteminfo",
    label: "Danh mục chỉ số ẩn (iteminfo)",
    group: "Vật phẩm",
    pk: ["ID"],
    autoIncrement: true,
    searchCols: ["ID", "name"],
    note: "Không có PRIMARY KEY thật, chỉ UNIQUE(ID) — dùng ID làm khoá.",
    columns: [
      { name: "ID", label: "ID", type: "int" },
      { name: "name", label: "Tên chỉ số", type: "string" },
      { name: "isPercent", label: "Là chỉ số %", type: "bool" },
    ],
  },
  {
    db: "game",
    table: "shop",
    label: "Shop",
    group: "Shop",
    pk: ["id"],
    autoIncrement: true,
    searchCols: ["id", "ShopId", "itemTemTempleId", "petId"],
    columns: [
      { name: "id", label: "ID", type: "int" },
      { name: "ShopId", label: "Mã shop", type: "int" },
      { name: "inventoryType", label: "Loại kho", type: "int" },
      { name: "itemTemTempleId", label: "Item bán", type: "ref", ref: "item", nullable: true },
      { name: "petId", label: "Pet bán", type: "ref", ref: "pet", nullable: true },
      { name: "count", label: "Số lượng", type: "int" },
      { name: "isSellItem", label: "Đang bán", type: "bool" },
      { name: "moneyType", label: "Loại tiền (JSON)", type: "json" },
      { name: "price", label: "Giá (JSON, khớp thứ tự moneyType)", type: "json" },
      { name: "clanLvl", label: "Bang hội cấp tối thiểu", type: "int" },
      { name: "perCount", label: "Giới hạn mua/ngày (0 = không giới hạn)", type: "int" },
    ],
  },
  {
    db: "game",
    table: "shoparena",
    label: "Shop lôi đài",
    group: "Shop",
    pk: ["Id"],
    autoIncrement: true,
    searchCols: ["Id", "itemTemTempleId"],
    columns: [
      { name: "Id", label: "ID", type: "int" },
      { name: "percent", label: "Tỉ lệ % giá", type: "float" },
      { name: "moneyType", label: "Loại tiền (JSON)", type: "json" },
      { name: "price", label: "Giá (JSON)", type: "json" },
      { name: "itemTemTempleId", label: "Item bán", type: "ref", ref: "item" },
      { name: "count", label: "Số lượng", type: "int" },
    ],
  },
  {
    db: "game",
    table: "drop_item",
    label: "Rơi đồ",
    group: "Shop",
    pk: ["dropId"],
    autoIncrement: true,
    searchCols: ["dropId", "mapId", "itemTemplateId"],
    columns: [
      { name: "dropId", label: "ID", type: "int" },
      { name: "mapId", label: "Bản đồ", type: "ref", ref: "map" },
      { name: "itemTemplateId", label: "Item rơi", type: "ref", ref: "item" },
      { name: "percent", label: "Tỉ lệ %", type: "float" },
      { name: "lvlRange", label: "Khoảng cấp quái (JSON [từ,đến])", type: "json", nullable: true },
      { name: "count", label: "Số lượng", type: "int" },
    ],
  },
  {
    db: "game",
    table: "trade_gift",
    label: "Quà đổi (trade_gift)",
    group: "Shop",
    pk: ["TradeId"],
    autoIncrement: true,
    searchCols: ["TradeId", "ItemTemplateId"],
    columns: [
      { name: "TradeId", label: "ID", type: "int" },
      { name: "ItemTemplateId", label: "Item", type: "ref", ref: "item" },
      { name: "Count", label: "Số lượng", type: "int" },
      { name: "Type", label: "Loại", type: "int" },
      { name: "Percent", label: "Tỉ lệ %", type: "float" },
    ],
  },
];
