import type { TableConfig } from "./table-registry";

/** Nhóm "Nhiệm vụ / Thành tựu / Xăm" + "Nâng cấp" — soát từ `SHOW CREATE TABLE` (2026-09-26). */
export const PROGRESSION_TABLES: TableConfig[] = [
  {
    db: "game",
    table: "task",
    label: "Nhiệm vụ",
    group: "Nhiệm vụ / Thành tựu / Xăm",
    pk: ["taskId"],
    autoIncrement: true,
    searchCols: ["taskId", "name"],
    columns: [
      { name: "taskId", label: "ID", type: "int" },
      { name: "type", label: "Loại nhiệm vụ", type: "int", note: "Xem bảng task_type.taskType, không có FK ràng buộc chặt" },
      { name: "name", label: "Tên", type: "string" },
      { name: "description", label: "Mô tả", type: "string", long: true },
      { name: "guide", label: "Hướng dẫn", type: "string", long: true, nullable: true },
      { name: "task", label: "Điều kiện hoàn thành (JSON)", type: "json" },
      { name: "gift", label: "Phần thưởng (JSON)", type: "json" },
      { name: "fromNPC", label: "NPC giao nhiệm vụ", type: "ref", ref: "npc" },
      { name: "taskNeed", label: "Nhiệm vụ cần trước (JSON id)", type: "json" },
    ],
  },
  {
    db: "game",
    table: "task_type",
    label: "Loại nhiệm vụ",
    group: "Nhiệm vụ / Thành tựu / Xăm",
    pk: ["taskType"],
    searchCols: ["taskType", "name"],
    columns: [
      { name: "taskType", label: "ID loại", type: "int" },
      { name: "name", label: "Tên", type: "string" },
    ],
  },
  {
    db: "game",
    table: "achievement",
    label: "Thành tựu",
    group: "Nhiệm vụ / Thành tựu / Xăm",
    pk: ["IdTemplate"],
    autoIncrement: true,
    searchCols: ["IdTemplate", "Name"],
    columns: [
      { name: "IdTemplate", label: "ID", type: "int" },
      { name: "Name", label: "Tên", type: "string" },
      { name: "Description", label: "Mô tả", type: "string", long: true },
      { name: "IconPath", label: "Đường dẫn icon", type: "string" },
      { name: "FramePath", label: "Đường dẫn frame", type: "string" },
      { name: "IsVertically", label: "Frame dọc", type: "bool" },
      { name: "FrameNum", label: "Số khung ảnh", type: "int" },
      { name: "Atk", label: "Atk", type: "int" },
      { name: "Def", label: "Def", type: "int" },
      { name: "Hp", label: "Hp", type: "int" },
      { name: "Mp", label: "Mp", type: "int" },
      { name: "Int", label: "Int", type: "int" },
      { name: "Str", label: "Str", type: "int" },
      { name: "Agi", label: "Agi", type: "int" },
      { name: "Expire", label: "Hạn dùng (ms, 0 = vĩnh viễn)", type: "bigint" },
      { name: "vX", label: "Lệch ngang (vX)", type: "int" },
      { name: "vY", label: "Lệch dọc (vY)", type: "int" },
    ],
  },
  {
    db: "game",
    table: "tattoo",
    label: "Xăm (tattoo)",
    group: "Nhiệm vụ / Thành tựu / Xăm",
    pk: ["tattooId"],
    autoIncrement: true,
    searchCols: ["tattooId", "name"],
    columns: [
      { name: "tattooId", label: "ID", type: "int" },
      { name: "name", label: "Tên", type: "string" },
      { name: "type", label: "Loại (-1 = mọi loại)", type: "int" },
      { name: "iconPath", label: "Đường dẫn icon", type: "string" },
      { name: "atk", label: "Atk", type: "int" },
      { name: "def", label: "Def", type: "int" },
      { name: "hp", label: "Hp", type: "int" },
      { name: "mp", label: "Mp", type: "int" },
      { name: "percent", label: "Tỉ lệ %", type: "float" },
    ],
  },
  {
    db: "game",
    table: "enchant_wing_data",
    label: "Cường hoá cánh",
    group: "Nâng cấp",
    pk: ["Level"],
    searchCols: ["Level"],
    columns: [
      { name: "Level", label: "Cấp cường hoá", type: "int" },
      { name: "Percent", label: "Tỉ lệ % thành công", type: "float" },
      { name: "Coin", label: "Coin cần", type: "int" },
      { name: "Gold", label: "Gold cần", type: "int" },
      { name: "NumDropLevelWing", label: "Số cấp rớt khi thất bại", type: "int" },
      { name: "NumItemMaterial", label: "Số nguyên liệu cần", type: "int" },
    ],
  },
  {
    db: "game",
    table: "reincarnation",
    label: "Trùng sinh pet",
    group: "Nâng cấp",
    pk: ["Id"],
    autoIncrement: true,
    searchCols: ["Id", "PetId", "PetIdReincarnation"],
    note: "PetId và PetIdReincarnation là UNIQUE riêng — mỗi pet chỉ xuất hiện 1 lần ở mỗi cột.",
    columns: [
      { name: "Id", label: "ID", type: "int" },
      { name: "PetId", label: "Pet cần", type: "ref", ref: "pet" },
      { name: "NumCard", label: "Số thẻ trùng sinh cần", type: "int" },
      { name: "PetIdReincarnation", label: "Pet sau trùng sinh", type: "ref", ref: "pet" },
    ],
  },
];
