import type { TableConfig } from "./table-registry";

/** Nhóm "Pet" — soát cột/PK từ `SHOW CREATE TABLE` (2026-09-26). */
export const PET_TABLES: TableConfig[] = [
  {
    db: "game",
    table: "gopet_pet",
    label: "Pet",
    group: "Pet",
    pk: ["petId"],
    searchCols: ["petId", "name"],
    refCheck: { playerColumn: "pets", jsonKey: "petIdTemplate" },
    columns: [
      { name: "petId", label: "ID", type: "int" },
      { name: "name", label: "Tên", type: "string", nullable: true },
      { name: "icon", label: "Đường dẫn icon", type: "string", nullable: true },
      { name: "frameImg", label: "Đường dẫn frame", type: "string", nullable: true },
      { name: "frameNum", label: "Số khung ảnh", type: "int" },
      { name: "vY", label: "Lệch dọc (vY)", type: "int" },
      { name: "hp", label: "HP", type: "int" },
      { name: "mp", label: "MP", type: "int" },
      { name: "str", label: "STR", type: "int", nullable: true },
      { name: "_int", label: "INT", type: "int", nullable: true },
      { name: "agi", label: "AGI", type: "int", nullable: true },
      { name: "type", label: "Loại", type: "int" },
      { name: "nclass", label: "Phái", type: "int", note: "Xem bảng Phái pet (pet_class.classId), không có FK ràng buộc" },
      { name: "element", label: "Hệ", type: "int", note: "Xem bảng Hệ pet (pet_element.elementId), không có FK ràng buộc" },
      { name: "gymUpLevel", label: "Cấp tập gym", type: "int" },
      { name: "FusionScore", label: "Điểm dung hợp", type: "int" },
    ],
  },
  {
    db: "game",
    table: "pet_class",
    label: "Phái pet",
    group: "Pet",
    pk: ["classId"],
    autoIncrement: true,
    searchCols: ["classId", "name"],
    columns: [
      { name: "classId", label: "ID", type: "int" },
      { name: "name", label: "Tên phái", type: "string" },
    ],
  },
  {
    db: "game",
    table: "pet_element",
    label: "Hệ pet",
    group: "Pet",
    pk: ["elementId"],
    autoIncrement: true,
    searchCols: ["elementId", "name"],
    columns: [
      { name: "elementId", label: "ID", type: "int" },
      { name: "name", label: "Tên hệ", type: "string", nullable: true },
    ],
  },
  {
    db: "game",
    table: "pet_tier",
    label: "Lai tạo pet (tier)",
    group: "Pet",
    pk: ["tierId"],
    autoIncrement: true,
    searchCols: ["tierId", "petTemplateId1", "petTemplateId2", "petTemplateIdNeed"],
    columns: [
      { name: "tierId", label: "ID", type: "int" },
      { name: "petTemplateId1", label: "Pet cha", type: "ref", ref: "pet" },
      { name: "petTemplateId2", label: "Pet mẹ", type: "ref", ref: "pet" },
      { name: "petTemplateIdNeed", label: "Pet kết quả", type: "ref", ref: "pet" },
    ],
  },
  {
    db: "game",
    table: "pet_eff",
    label: "Hiệu ứng pet (pet_eff)",
    group: "Pet",
    pk: ["Id"],
    autoIncrement: true,
    searchCols: ["Id", "Name"],
    columns: [
      { name: "Id", label: "ID", type: "int" },
      { name: "Type", label: "Loại", type: "int" },
      { name: "Name", label: "Tên", type: "string" },
      { name: "Description", label: "Mô tả", type: "string", long: true },
      { name: "IconPath", label: "Đường dẫn icon", type: "string" },
      { name: "FramePath", label: "Đường dẫn frame", type: "string" },
      { name: "FrameNum", label: "Số khung ảnh", type: "int" },
      { name: "Atk", label: "Atk", type: "int" },
      { name: "Def", label: "Def", type: "int" },
      { name: "Hp", label: "Hp", type: "int" },
      { name: "Mp", label: "Mp", type: "int" },
      { name: "Int", label: "Int", type: "int" },
      { name: "Str", label: "Str", type: "int" },
      { name: "Agi", label: "Agi", type: "int" },
      { name: "vX", label: "Lệch ngang (vX)", type: "int" },
      { name: "vY", label: "Lệch dọc (vY)", type: "int" },
      { name: "IsDrawBefore", label: "Vẽ trước nhân vật", type: "bool" },
      { name: "FrameTime", label: "Thời gian mỗi khung (ms)", type: "int" },
    ],
  },
  {
    db: "game",
    table: "petexp",
    label: "Bảng exp lên cấp pet",
    group: "Pet",
    pk: ["petLvl"],
    searchCols: ["petLvl"],
    columns: [
      { name: "petLvl", label: "Cấp pet", type: "int" },
      { name: "exp", label: "Exp cần", type: "int" },
    ],
  },
  {
    db: "game",
    table: "hidden_stat",
    label: "Chỉ số ẩn theo bộ trang bị",
    group: "Pet",
    pk: ["Id"],
    autoIncrement: true,
    searchCols: ["Id", "Comment"],
    note: "5 cột IdWeapon/IdHat/IdArmour/IdShoe/IdGlove là UNIQUE tổ hợp — trùng bộ sẽ báo lỗi khi lưu.",
    columns: [
      { name: "Id", label: "ID", type: "int" },
      { name: "IdWeapon", label: "Vũ khí", type: "ref", ref: "item", nullable: true },
      { name: "IdHat", label: "Mũ", type: "ref", ref: "item", nullable: true },
      { name: "IdArmour", label: "Áo giáp", type: "ref", ref: "item", nullable: true },
      { name: "IdShoe", label: "Giày", type: "ref", ref: "item", nullable: true },
      { name: "IdGlove", label: "Găng tay", type: "ref", ref: "item", nullable: true },
      { name: "Data", label: "Chỉ số cộng thêm (JSON)", type: "json" },
      { name: "Comment", label: "Ghi chú", type: "string", long: true },
    ],
  },
];
