import type { TableConfig } from "./table-registry";

/** Nhóm "Bản đồ & NPC" + "Quái" — soát cột/PK từ `SHOW CREATE TABLE` (2026-09-26). */
export const WORLD_TABLES: TableConfig[] = [
  {
    db: "game",
    table: "npc",
    label: "NPC",
    group: "Bản đồ & NPC",
    pk: ["npcId"],
    autoIncrement: true,
    searchCols: ["npcId", "name"],
    columns: [
      { name: "npcId", label: "ID", type: "int" },
      { name: "name", label: "Tên", type: "string" },
      { name: "chat", label: "Câu chat", type: "string", long: true },
      { name: "optionName", label: "Tên lựa chọn hội thoại (JSON)", type: "json" },
      { name: "optionId", label: "ID lựa chọn hội thoại (JSON)", type: "json" },
      { name: "x", label: "Toạ độ x", type: "int" },
      { name: "y", label: "Toạ độ y", type: "int" },
      { name: "imgPath", label: "Ảnh hội thoại", type: "string" },
      { name: "type", label: "Loại NPC", type: "int" },
      { name: "bounds", label: "Vùng va chạm (JSON [x,y,w,h])", type: "json" },
    ],
  },
  {
    db: "game",
    table: "map",
    label: "Bản đồ",
    group: "Bản đồ & NPC",
    pk: ["mapId"],
    searchCols: ["mapId", "name"],
    columns: [
      { name: "mapId", label: "ID", type: "int" },
      { name: "name", label: "Tên", type: "string" },
      { name: "npc", label: "Danh sách NPC (JSON id)", type: "json" },
      { name: "boss", label: "Danh sách boss (JSON id)", type: "json" },
      {
        name: "numPetDie",
        label: "Số quái cần giết để triệu hồi boss (JSON)",
        type: "json",
        note: "Nhớ: map 19 đang là giá trị test [5] (gốc [500]) — khôi phục khi hết test.",
      },
      { name: "enable", label: "Bật bản đồ", type: "bool" },
    ],
  },
  {
    db: "game",
    table: "gopet_map_moblvl",
    label: "Cấp quái theo bản đồ",
    group: "Bản đồ & NPC",
    pk: ["mapID", "petId", "lvlFrom", "lvlTo"],
    searchCols: ["mapID", "petId"],
    note: "Khoá chính ghép (mapID, petId, lvlFrom, lvlTo) — không tự sinh, phải nhập đủ khi tạo.",
    columns: [
      { name: "mapID", label: "Bản đồ", type: "ref", ref: "map" },
      { name: "petId", label: "Pet (mẫu quái)", type: "ref", ref: "pet" },
      { name: "lvlFrom", label: "Cấp từ", type: "int" },
      { name: "lvlTo", label: "Cấp đến", type: "int" },
    ],
  },
  {
    db: "game",
    table: "boss",
    label: "Boss",
    group: "Quái",
    pk: ["bossId"],
    autoIncrement: true,
    searchCols: ["bossId", "name", "petTemplateId"],
    columns: [
      { name: "bossId", label: "ID", type: "int" },
      { name: "petTemplateId", label: "Mẫu pet", type: "ref", ref: "pet" },
      { name: "name", label: "Tên", type: "string" },
      { name: "str", label: "STR", type: "int" },
      { name: "_int", label: "INT", type: "int" },
      { name: "agi", label: "AGI", type: "int" },
      { name: "lvl", label: "Cấp", type: "int" },
      { name: "typeBoss", label: "Loại boss", type: "int" },
      { name: "gift", label: "Quà rơi (JSON)", type: "json" },
      { name: "exp", label: "Exp thưởng", type: "int" },
      { name: "HourSummon", label: "Giờ triệu hồi (JSON)", type: "json", nullable: true },
      { name: "BossMapSummon", label: "Bản đồ triệu hồi (JSON id)", type: "json", nullable: true },
      { name: "atk", label: "Atk", type: "int" },
      { name: "hp", label: "HP", type: "int" },
    ],
  },
  {
    db: "game",
    table: "gopet_mob",
    label: "Chỉ số quái theo cấp (gopet_mob)",
    group: "Quái",
    pk: [],
    readOnly: true,
    searchCols: ["lvl"],
    note: "Không có PRIMARY KEY trong DB → chỉ xem, không sửa/xoá qua khung này.",
    columns: [
      { name: "lvl", label: "Cấp", type: "int" },
      { name: "str", label: "STR", type: "int" },
      { name: "_int", label: "INT", type: "int" },
      { name: "agi", label: "AGI", type: "int" },
      { name: "exp", label: "Exp", type: "int" },
      { name: "coin", label: "Coin", type: "int" },
      { name: "hp", label: "HP", type: "int" },
      { name: "atk", label: "Atk (NULL = công thức str/3 cũ)", type: "int", nullable: true },
      { name: "def", label: "Def (NULL = công thức agi/3 cũ)", type: "int", nullable: true },
    ],
  },
  {
    db: "game",
    table: "gopet_mob_location",
    label: "Vị trí quái",
    group: "Quái",
    pk: ["mapID", "x", "y"],
    searchCols: ["mapID"],
    note: "Khoá chính ghép (mapID, x, y).",
    columns: [
      { name: "mapID", label: "Bản đồ", type: "ref", ref: "map" },
      { name: "x", label: "Toạ độ x", type: "int" },
      { name: "y", label: "Toạ độ y", type: "int" },
    ],
  },
];
