// <auto-generated>
//     Sinh bởi tools/gen-gopet-cmd. KHÔNG sửa tay.
//     Nguồn: SRCGOPETGOC/GServer/Server/GopetCMD.cs
//     Sinh lại: node tools/gen-gopet-cmd/index.js
// </auto-generated>

namespace Gopet.Net
{
    /// <summary>
    /// Opcode giao thức, phản chiếu nguyên văn <c>GopetCMD.cs</c> của server.
    /// Nhiều hằng số trùng giá trị vì chúng là sub-command trong ngữ cảnh khác nhau.
    /// </summary>
    public static partial class GopetCmd
    {
        public const sbyte ON_PLACE_CHAT = 9;
        public const sbyte CHAT_PUBLIC = 66;
        public const sbyte CLAN = 91;
        public const sbyte CLAN_INFO_MEMBER = 3;
        public const sbyte CLAN_INFO = 14;
        public const sbyte DONATE_CLAN = 9;
        public const sbyte GUILD_LIST = 1;
        public const sbyte GUILD_JOIN = 2;
        public const sbyte GUILD_LIST_MEMBER = 3;
        public const sbyte GUILD_KICK_MEMBER = 6;
        public const sbyte SEARCH_GUILD = 13;
        public const sbyte PLAYER_DONATE_CLAN = 10;
        public const sbyte GUILD_TOP_FUND = 16;
        public const sbyte GUILD_TOP_GROWTH_POINT = 15;
        public const sbyte GUILD_NAME_IN_PLACE = 23;
        public const sbyte GUILD_REQUEST_JOIN = 2;
        public const sbyte GUILD_CHAT = 20;
        public const sbyte GUILD_PLAYER_CHAT = 21;
        public const sbyte GUILD_ON_PLAYER_CHAT = 22;
        public const sbyte GUILD_CLAN_SKILL = 24;
        public const sbyte GUILD_CLAN_UNLOCK_SKILL = 25;
        public const sbyte GUILD_CLAN_RENT_SKILL = 26;
        public const sbyte GUILD_SHOW_OHTER_PLAYER_CLAN_SKILL = 27;
        public const sbyte SKILL_CLAN_LOCK = -1;
        public const sbyte SKILL_CLAN_RENT = 0;
        public const sbyte SKILL_CLAN_CHANGE = 1;
        public const sbyte LETTER_COMMAND = 121;
        public const sbyte LETTER_COMMAND_LIST_FRIEND = 1;
        public const sbyte LETTER_COMMAND_LIST_REQUEST_ADD_FRIEND = 2;
        public const sbyte LETTER_COMMAND_REQUEST_ADD_FRIEND = 3;
        public const sbyte LETTER_COMMAND_REQUEST_ADD_FRIEND_WITH_NAME = 4;
        public const sbyte LETTER_COMMAND_LIST_BLOCK_FRIEND = 10;
        public const sbyte LETTER_COMMAND_SEND_LETTER = 15;
        public const sbyte LETTER_COMMAND_SET_MARK = 16;
        public const sbyte LETTER_COMMAND_REMOVE_LETTER = 17;
        public const sbyte LETTER_COMMAND_HAS_LETTER = 18;
        public const sbyte LETTER_BOX = 13;
        public const sbyte CHAT_GLOBAL = 10;
    }
}
