public final class dn {
   public int a;
   public String a;
   public String b;
   public byte a;
   public int b;
   public long a;
   public long b;
   public long c;
   public int c;
   public int d;
   public int e;
   public int f;
   public int g;
   public int h;
   public int i;
   public int j;
   public int k;
   public String[] a;
   public String[] b;
   public int[] a;
   public int[] b;
   public String[] c;
   public int l;
   public byte b;
   public byte c;
   public short a = 0;
   public int m;
   public boolean a = false;
}
