#!/usr/bin/env node
/**
 * Sinh Assets/Scripts/Net/GopetCmd.cs từ GServer/Server/GopetCMD.cs.
 *
 * Opcode là hợp đồng giữa client và server. Gõ tay 177 hằng số là sẽ sai,
 * và sai opcode thì lỗi hiện ra ở tận đâu. Chạy lại script này mỗi khi
 * server đổi GopetCMD.cs.
 *
 * Dùng: node index.js [--check]
 *   --check  chỉ so sánh, không ghi. Exit 1 nếu lệch (dùng cho CI).
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const SERVER_CMD = path.join(REPO_ROOT, 'SRCGOPETGOC', 'GServer', 'Server', 'GopetCMD.cs');
const OUT_FILE = path.join(REPO_ROOT, 'GopetUnityClient', 'Assets', 'Scripts', 'Net', 'GopetCmd.cs');

/** `public const sbyte NAME = -36;` / `public const int NAME = 3;` */
const CONST_RE = /public\s+const\s+(sbyte|int|short|byte)\s+([A-Za-z_]\w*)\s*=\s*(-?\d+)\s*;/g;

/** Doc comment kiểu Java `/** ... *\/` ngay trước hằng số. */
const DOC_RE = /\/\*\*([\s\S]*?)\*\//g;

function parse(source) {
    // Thu doc comment theo vị trí kết thúc để gán cho hằng số ngay sau nó.
    const docs = [];
    let d;
    while ((d = DOC_RE.exec(source)) !== null) {
        const text = d[1]
            .split('\n')
            .map((l) => l.replace(/^\s*\*?\s?/, '').trimEnd())
            .filter((l) => l.length > 0)
            .join(' ');
        if (text) docs.push({ end: d.index + d[0].length, text });
    }

    const entries = [];
    const seen = new Map();
    let m;
    while ((m = CONST_RE.exec(source)) !== null) {
        const [, type, name, value] = m;

        // Doc gần nhất kết thúc trước hằng số này, và chỉ cách bởi khoảng trắng.
        let doc = null;
        for (let i = docs.length - 1; i >= 0; i--) {
            if (docs[i].end <= m.index) {
                if (/^\s*$/.test(source.slice(docs[i].end, m.index))) doc = docs[i].text;
                break;
            }
        }

        // Server có hằng số trùng giá trị ở namespace khác nhau (vd ON_PLAYER_ENTER_MAP
        // và ON_PLAYER_CHANGE_CHANNEL đều = 24). Tên trùng thì mới là lỗi.
        if (seen.has(name)) {
            throw new Error(`Hằng số trùng tên trong GopetCMD.cs: ${name}`);
        }
        seen.set(name, value);
        entries.push({ type, name, value: parseInt(value, 10), doc });
    }
    return entries;
}

function csharpType(t) {
    // sbyte giữ nguyên: opcode có giá trị âm (CLIENT_INFO = -36).
    return t === 'byte' ? 'byte' : t;
}

function emit(entries) {
    const lines = [
        '// <auto-generated>',
        '//     Sinh bởi tools/gen-gopet-cmd. KHÔNG sửa tay.',
        '//     Nguồn: SRCGOPETGOC/GServer/Server/GopetCMD.cs',
        '//     Sinh lại: node tools/gen-gopet-cmd/index.js',
        '// </auto-generated>',
        '',
        'namespace Gopet.Net',
        '{',
        '    /// <summary>',
        '    /// Opcode giao thức, phản chiếu nguyên văn <c>GopetCMD.cs</c> của server.',
        '    /// Nhiều hằng số trùng giá trị vì chúng là sub-command trong ngữ cảnh khác nhau.',
        '    /// </summary>',
        '    public static partial class GopetCmd',
        '    {',
    ];

    for (const e of entries) {
        if (e.doc) {
            lines.push(`        /// <summary>${e.doc.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</summary>`);
        }
        lines.push(`        public const ${csharpType(e.type)} ${e.name} = ${e.value};`);
    }

    lines.push('    }', '}', '');
    return lines.join('\n');
}

function main() {
    const checkOnly = process.argv.includes('--check');

    if (!fs.existsSync(SERVER_CMD)) {
        console.error(`Không tìm thấy nguồn: ${SERVER_CMD}`);
        process.exit(1);
    }

    const entries = parse(fs.readFileSync(SERVER_CMD, 'utf8'));
    if (entries.length === 0) {
        console.error('Không parse được hằng số nào — kiểm tra lại regex hoặc file nguồn.');
        process.exit(1);
    }

    // Keep social command families together in a generated partial instead of
    // dropping server aliases or exempting a growing generated file from checks.
    const social = e => /GUILD|CLAN|LETTER|FRIEND|CHAT/.test(e.name);
    const outputs = [
        [OUT_FILE, emit(entries.filter(e => !social(e)))],
        [OUT_FILE.replace('.cs', '.Social.cs'), emit(entries.filter(social))],
    ];
    for (const [file, generated] of outputs) {
        // Windows checkouts may apply core.autocrlf; line endings are not protocol drift.
        const existing = fs.existsSync(file)
            ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null;
        if (checkOnly) {
            if (existing !== generated) {
                console.error(`${path.basename(file)} differs from server constants. Run npm run gen:cmd.`);
                process.exitCode = 1;
            }
        } else {
            fs.mkdirSync(path.dirname(file), { recursive: true });
            fs.writeFileSync(file, generated, 'utf8');
        }
    }
    if (!process.exitCode) console.log(`OK - ${entries.length} constants across ${outputs.length} files.`);

}

main();
